### ISSUE TITLE
Error with CSP

### ISSUE THREAD

**Issue by dragoonzx** [xiaoluoboding/vitesse-modernized-chrome-ext#1]
Refused to load the script 'http://localhost:3309/popup/main.ts' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Maybe you can help, where to dig in?

**Comment by dragoonzx** [comment]
It seems like there is [a problem with manifest v3](https://bugs.chromium.org/p/chromium/issues/detail?id=1247690)

**Comment by xiaoluoboding** [comment]
@dragoonzx 

Yeah, this problem only appeared recently. 
This repo was created almost three months, at that time, the latest stable Chrome version is 91.x.

So. I download the old version(91.0.4472.114) of Chrome and it works. It seems like the latest Chrome blocked the CSP Config in manifest v3.

You could use this repo: [https://github.com/antfu/vitesse-webext](https://github.com/antfu/vitesse-webext) as the starter which supports manifest v2 or download an old version of Chrome which under 91.x, notice that can not allow chrome auto-upgrade

**Comment by goelrohan6** [comment]
what's a good solution here @xiaoluoboding, does something needs to change in `manifest.content_security_policy`?
as the users which we send this extension to won't downgrade their browser version

**Comment by xiaoluoboding** [comment]
See https://github.com/xiaoluoboding/vitesse-modernized-chrome-ext/pull/5
