### ISSUE TITLE
An error is reported after executing the pnpm dev command

### ISSUE THREAD

**Issue by zhanyeye** [xiaoluoboding/vitesse-modernized-chrome-ext#3]
When I run the `npm dev` command I get the following error (Missing `manifest.json` file):
> 当我运行 `npm dev` 命令后会出现以下错误 （缺少`manifest.json`文件）：

```
[Error: ENOENT: no such file or directory, open 'C:\Users\****\extension\dev\manifest.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\****\\extension\\dev\\manifest.json'
}
ERROR: "dev:prepare" exited with 1.
```

should I need additional configuration to run the project?
> 是否需要额外的配置来运行项目呀?

**Comment by xiaoluoboding** [comment]
https://github.com/xiaoluoboding/vitesse-modernized-chrome-ext/commit/bda5b61b079ca3ea0c07ebc04532260b77223de5
