### ISSUE TITLE
Question: Why need to use Manifest V2 in dev enviroment?

### ISSUE THREAD

**Issue by GarinZ** [xiaoluoboding/vitesse-modernized-chrome-ext#7]
[Question1] I want to confirm that why in this template we need to use Manifest V2 in dev enviroment?

Is that because Manifest V3 modified the rules on CSP(Content Security Policy), so that we no longer could use vite HRM？

[Question2] If in dev env we have to use Manifest V2 syntax, is there any good pratice to make it easy to deal  with V2&V3 Chrome API？

**Comment by xiaoluoboding** [comment]
@GarinZ 

[Answer1] Yes

[Answer 2] We can't actually use MV3 in development, I'm considering removing MV2 In development, after all Chrome will no longer support the MV2 API
