### ISSUE TITLE
manifest-v3 can't load main.ts

### ISSUE THREAD

**Issue by tjx666** [xiaoluoboding/vitesse-modernized-chrome-ext#8]
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/41773861/202894435-8b8b56d1-d2d5-480e-9c7f-99091f150474.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/202894446-07c5918e-bc3e-4abf-8801-10521ef84f4f.png">

**Comment by xiaoluoboding** [comment]
Some as #4
